FROM registry.access.redhat.com/ubi9/nodejs-24-minimal:9.8-1781562052 AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

FROM registry.access.redhat.com/hi/nginx:1

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/templates/default.conf.template

EXPOSE 8080

CMD ["-g", "daemon off;"]
