pipeline 
{
   agent any
   
   options 
   {
      disableConcurrentBuilds()
      buildDiscarder(logRotator(numToKeepStr: '2'))
   }

   stages
   {
      stage('Prepare') 
      {
         steps 
         {
            sh '''
                    echo "PATH = ${PATH}"
                '''

            git branch: 'main', 
                url: 'https://github.com/glroland/agent_patches.git'
         }
      }

      stage('Create Docker Image for central-ui') 
      {
         steps 
         {
            sh 'cd central-ui ; docker build -f Containerfile --tag central-ui:$BUILD_NUMBER .'
            sh 'cd central-ui ; docker save central-ui:$BUILD_NUMBER > central-ui-dockerimage.tar'
            step(followSymlinks: false, artifacts: 'central-ui/central-ui-dockerimage.tar', $class: 'ArtifactArchiver')
            sh 'cd central-ui ; docker rmi central-ui:$BUILD_NUMBER'
         }
      }

      stage('Create Docker Image for central-backend') 
      {
         steps 
         {
            sh 'cd central-backend ; docker build -f Dockerfile --tag central-backend:$BUILD_NUMBER .'
            sh 'cd central-backend ; docker save central-backend:$BUILD_NUMBER > central-backend-dockerimage.tar'
            step(followSymlinks: false, artifacts: 'central-backend/central-backend-dockerimage.tar', $class: 'ArtifactArchiver')
            sh 'cd central-backend ; docker rmi central-backend:$BUILD_NUMBER'
         }
      }

      stage('Reload then push images to quay') 
      {
         steps 
         {
            script 
            {
               docker.withRegistry('https://registry.home.glroland.com/', 'quay') 
               {
                  sh 'docker load -i central-ui/central-ui-dockerimage.tar'
                  sh 'docker tag central-ui:$BUILD_NUMBER registry.home.glroland.com/agent_patches/central-ui:$BUILD_NUMBER'
                  sh 'docker rmi central-ui:$BUILD_NUMBER'
                  sh 'docker push registry.home.glroland.com/agent_patches/central-ui:$BUILD_NUMBER'
                  sh 'docker rmi registry.home.glroland.com/agent_patches/central-ui:$BUILD_NUMBER'

                  sh 'docker load -i central-backend/central-backend-dockerimage.tar'
                  sh 'docker tag central-backend:$BUILD_NUMBER registry.home.glroland.com/agent_patches/central-backend:$BUILD_NUMBER'
                  sh 'docker rmi central-backend:$BUILD_NUMBER'
                  sh 'docker push registry.home.glroland.com/agent_patches/central-backend:$BUILD_NUMBER'
                  sh 'docker rmi registry.home.glroland.com/agent_patches/central-backend:$BUILD_NUMBER'
               }
            }
         }
      }
   }
}
