apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  host: {{ printf "%s-backend.%s" .Release.Name .Values.global.clusterDomain }}
  to:
    kind: Service
    name: {{ .Chart.Name }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
