apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
   AGENT_AUTH_TOKEN: {{ .Values.secret.data.AGENT_AUTH_TOKEN | b64enc | quote }}
